# Generated by Django 3.2 on 2025-04-05 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bath',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop_app.product', verbose_name='Продукт')),
                ('length', models.PositiveIntegerField(verbose_name='Длина, см')),
                ('width', models.PositiveIntegerField(verbose_name='Ширина, см')),
                ('depth', models.PositiveIntegerField(verbose_name='Глубина, см')),
                ('thickness', models.PositiveIntegerField(verbose_name='Толщина, мм')),
                ('completeness', models.CharField(db_index=True, max_length=200, verbose_name='Комплектность')),
                ('coating', models.BooleanField(default=True, verbose_name='Антискользящее покрытие')),
                ('hydromassage', models.BooleanField(default=True, verbose_name='Гидромассаж')),
                ('form', models.CharField(db_index=True, max_length=200, verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Ванна или поддон',
                'verbose_name_plural': 'Ванны и поддоны',
            },
        ),
        migrations.CreateModel(
            name='Bathroom_accessories',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop_app.product', verbose_name='Продукт')),
                ('size', models.CharField(db_index=True, max_length=50, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Аксессуар для ванной',
                'verbose_name_plural': 'Аксессуары для ванной',
            },
        ),
        migrations.CreateModel(
            name='Faucet',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop_app.product', verbose_name='Продукт')),
                ('mounting', models.CharField(db_index=True, max_length=200, verbose_name='Способ монтажа')),
                ('management', models.CharField(db_index=True, max_length=200, verbose_name='Управление')),
                ('size', models.CharField(db_index=True, max_length=50, verbose_name='Размер')),
                ('spout', models.CharField(db_index=True, max_length=200, verbose_name='Излив')),
                ('appointment', models.CharField(db_index=True, max_length=200, verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Смеситель или система для душа',
                'verbose_name_plural': 'Смесители и системы для душа',
            },
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop_app.product', verbose_name='Продукт')),
                ('length', models.PositiveIntegerField(verbose_name='Длина, см')),
                ('width', models.PositiveIntegerField(verbose_name='Ширина, см')),
                ('depth', models.PositiveIntegerField(verbose_name='Глубина, см')),
                ('shell_material', models.CharField(db_index=True, max_length=200, verbose_name='Материал раковины')),
                ('facade_material', models.CharField(db_index=True, max_length=200, verbose_name='Материал фасада')),
                ('mounting', models.CharField(db_index=True, max_length=200, verbose_name='Способ монтажа')),
                ('backlight', models.BooleanField(default=True, verbose_name='Подсветка')),
            ],
            options={
                'verbose_name': 'Мебель для ванной',
                'verbose_name_plural': 'Мебель для ванной',
            },
        ),
        migrations.CreateModel(
            name='Plumbing',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop_app.product', verbose_name='Продукт')),
                ('size', models.CharField(db_index=True, max_length=50, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Инженерная сантехника',
                'verbose_name_plural': 'Инженерная сантехника',
            },
        ),
        migrations.CreateModel(
            name='Sanfayance',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop_app.product', verbose_name='Продукт')),
                ('length', models.PositiveIntegerField(verbose_name='Длина, см')),
                ('width', models.PositiveIntegerField(verbose_name='Ширина, см')),
                ('depth', models.PositiveIntegerField(verbose_name='Глубина, см')),
                ('drain_mode', models.CharField(db_index=True, max_length=200, verbose_name='Режим слива воды')),
                ('mounting', models.CharField(db_index=True, max_length=200, verbose_name='Способ монтажа')),
                ('form', models.CharField(db_index=True, max_length=200, verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Санфаянс',
                'verbose_name_plural': 'Санфаянс',
            },
        ),
        migrations.CreateModel(
            name='Sink',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop_app.product', verbose_name='Продукт')),
                ('length', models.PositiveIntegerField(verbose_name='Длина, см')),
                ('width', models.PositiveIntegerField(verbose_name='Ширина, см')),
                ('depth', models.PositiveIntegerField(verbose_name='Глубина, см')),
                ('number_of_bowls', models.PositiveIntegerField(verbose_name='Количество чаш')),
                ('mounting', models.CharField(db_index=True, max_length=200, verbose_name='Способ монтажа')),
                ('shredder', models.BooleanField(default=True, verbose_name='Измельчитель отходов')),
                ('form', models.CharField(db_index=True, max_length=200, verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Кухонная мойка',
                'verbose_name_plural': 'Кухонные мойки',
            },
        ),
        migrations.CreateModel(
            name='Towel_rail',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop_app.product', verbose_name='Продукт')),
                ('length', models.PositiveIntegerField(verbose_name='Длина, см')),
                ('width', models.PositiveIntegerField(verbose_name='Ширина, см')),
                ('connection', models.CharField(db_index=True, max_length=200, verbose_name='Вид подключения')),
                ('type', models.CharField(db_index=True, max_length=200, verbose_name='Тип')),
                ('form', models.CharField(db_index=True, max_length=200, verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Полотенцесушитель',
                'verbose_name_plural': 'Полотенцесушители',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='art',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='Артикуль'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='maker',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Изготовитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Материал'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
